package GUI;

import DTO.*;
import BLL.*;
import DAL.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;

import java.awt.Image;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.*;


/**
 *
 * @author ACER
 */
public final class formquanly extends javax.swing.JFrame {

    DefaultTableModel Modelsp, Modelnv, Modelmenu, Modelhoadon, Modellshoadon;

    ArrayList<sanphamdao> spdao = CSDLQueryDao.XuatSanPhamDao();// ds san phẩm
    ArrayList<sanphamdao> spmenu = CSDLQueryDao.XuatSanPhamDao();// ds san phẩm bên menu
    ArrayList<nhanviendao> nvdao = CSDLQueryNV.XuatNV();        // ds nhân viên
    ArrayList<hoadondao> lshddao = CSDLQueryHD.XuatHoaDonDao();// ds lịch sử hóa đơn
    
    ArrayList<chitiethoadon> chitiet = new ArrayList<>();// ds lịch sử hóa đơn
     
    public static LocalDate lttime = LocalDate.now();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    DecimalFormat df = new DecimalFormat("###,###,###");

    public formquanly() {
        initComponents();
        tf_manv.setText(CSDLQueryNV.idNV);
        tf_tennv.setText(CSDLQueryNV.tenNV);
        setLocationRelativeTo(null);// căn giữa màn hình
        editAllTable(TableDao);
        editAllTable(TableMenu);
        editAllTable(TableHoadon);
        editAllTable(TableLSHD);
        editAllTable(TableNV);   
        /// xuất table
        xuatspDao(spdao);
        /// xuất table
        ImageIcon ic=new ImageIcon("../QuanLyBanNuoc/src/images/153-bar-chart-growth-outline.png");
        jButton4.setIcon(new ImageIcon(ic.getImage().getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), Image.SCALE_SMOOTH)));
    }

    public void editAllTable(JTable tb) {
        tb.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tb.getTableHeader().setOpaque(false);
        tb.getTableHeader().setBackground(new Color(32, 126, 203));
        tb.getTableHeader().setForeground(new Color(255, 255, 255));
        tb.setRowHeight(20);
    }

    public void xuatspDao(ArrayList<sanphamdao> daoList) {
        Modelsp = (DefaultTableModel) TableDao.getModel();
        Modelsp.setRowCount(0);
        int stt = 1;
        for (sanphamdao daoList1 : daoList) {
            Modelsp.addRow(new Object[]{
                stt++, daoList1.getMasp(), daoList1.getTensp(),daoList1.getSoluongsp() ,daoList1.getTinhtrangsp(), df.format(daoList1.getGiasp())
            });
        }
    }

    public void xuatnvDao(ArrayList<nhanviendao> nvList) {
        Modelnv = (DefaultTableModel) TableNV.getModel();
        Modelnv.setRowCount(0);
        for (nhanviendao nvList1 : nvList) {
            Modelnv.addRow(new Object[]{
                nvList1.getIdnv(), nvList1.getTennv(), nvList1.getDiachinv(), nvList1.getNgaysinhnv(), nvList1.getSdtnv()
            });
        }
    }

    public void xuatspMenu(ArrayList<sanphamdao> daoList) {
        Modelmenu = (DefaultTableModel) TableMenu.getModel();
        Modelmenu.setRowCount(0);
        int stt = 1;
        for (sanphamdao daoList1 : daoList) {
            Modelmenu.addRow(new Object[]{
                stt++, daoList1.getTensp(), df.format(daoList1.getGiasp()), daoList1.getSoluongsp(), daoList1.getTinhtrangsp(), daoList1.getMasp()
            });
        }
    }

    public void xuatlshoadon(ArrayList<hoadondao> hdList) {
        Modellshoadon = (DefaultTableModel) TableLSHD.getModel();
        Modellshoadon.setRowCount(0);
        int stt = 1;
        for (hoadondao hdList1 : hdList) {
            Modellshoadon.addRow(new Object[]{
                stt++, hdList1.getMahd(), hdList1.getNgayhd(), df.format(hdList1.getGiahd()), hdList1.getTenNVdh()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bnt_muahang = new javax.swing.JButton();
        bnt_lichsu = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnl_content = new javax.swing.JPanel();
        pnl_sanpham = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDao = new javax.swing.JTable();
        tf_timkiemsp = new javax.swing.JTextField();
        bnt_tksp = new javax.swing.JButton();
        tf_timkiemmasp = new javax.swing.JTextField();
        cbb_tkttsp = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tf_tensp = new javax.swing.JTextField();
        tf_giasp = new javax.swing.JTextField();
        bnt_themsp = new javax.swing.JButton();
        bnt_suasp = new javax.swing.JButton();
        bnt_xoasp = new javax.swing.JButton();
        cbb_ttsp = new javax.swing.JComboBox<>();
        tf_soluongsp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lb_anhSP = new javax.swing.JLabel();
        bnt_themanhSP = new javax.swing.JButton();
        tf_anhsp = new javax.swing.JTextField();
        pnl_muahang = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableMenu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tf_timspmenu = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tf_tspMenu = new javax.swing.JTextField();
        tf_slspMenu = new javax.swing.JTextField();
        bnt_themsoMenu = new javax.swing.JButton();
        tf_giaspMenu = new javax.swing.JTextField();
        tf_trthaisp = new javax.swing.JTextField();
        bnt_xoasphd = new javax.swing.JButton();
        tf_slconspMenu = new javax.swing.JTextField();
        tf_maspMenu = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableHoadon = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        tf_mahoadon = new javax.swing.JTextField();
        tf_ngayhoadon = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_manv = new javax.swing.JTextField();
        lb_tongtien = new javax.swing.JLabel();
        tf_tennv = new javax.swing.JTextField();
        bnt_thanhtoan = new javax.swing.JButton();
        pnl_lichsuhd = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableLSHD = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_ndlshd = new javax.swing.JTextArea();
        tf_tkhoadon = new javax.swing.JTextField();
        tf_dhnv = new javax.swing.JTextField();
        bnt_timcthd = new javax.swing.JButton();
        cbb1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        pnl_nhanvien = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNV = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lb_anhNV = new javax.swing.JLabel();
        tf_idNV = new javax.swing.JTextField();
        tf_tenNV = new javax.swing.JTextField();
        tf_diachiNV = new javax.swing.JTextField();
        bnt_xoaNV = new javax.swing.JButton();
        bnt_themNV = new javax.swing.JButton();
        bnt_suaNV = new javax.swing.JButton();
        tf_duongdananhNV = new javax.swing.JTextField();
        bnt_tkNV = new javax.swing.JButton();
        tf_tkidNV = new javax.swing.JTextField();
        tf_tktenNV = new javax.swing.JTextField();
        cld_nsNV = new com.toedter.calendar.JDateChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tf_sdtnv = new javax.swing.JTextField();
        btn_anhnv = new javax.swing.JButton();
        bnt_excelNV = new javax.swing.JButton();
        pnl_thongke = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        pnl_tk2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_menu.setBackground(new java.awt.Color(35, 43, 43));

        jButton1.setBackground(new java.awt.Color(65, 74, 76));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SẢN PHẨM");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(65, 74, 76));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("LOGOUT");
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(65, 74, 76));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NHÂN VIÊN");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        bnt_muahang.setBackground(new java.awt.Color(65, 74, 76));
        bnt_muahang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnt_muahang.setForeground(new java.awt.Color(255, 255, 255));
        bnt_muahang.setText("MUA HÀNG");
        bnt_muahang.setBorder(null);
        bnt_muahang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_muahangMouseClicked(evt);
            }
        });

        bnt_lichsu.setBackground(new java.awt.Color(65, 74, 76));
        bnt_lichsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bnt_lichsu.setForeground(new java.awt.Color(255, 255, 255));
        bnt_lichsu.setText("LỊCH SỬ");
        bnt_lichsu.setBorder(null);
        bnt_lichsu.setPreferredSize(new java.awt.Dimension(131, 49));
        bnt_lichsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_lichsuMouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_menuLayout = new javax.swing.GroupLayout(pnl_menu);
        pnl_menu.setLayout(pnl_menuLayout);
        pnl_menuLayout.setHorizontalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(bnt_muahang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bnt_lichsu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnl_menuLayout.setVerticalGroup(
            pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bnt_muahang, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bnt_lichsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(pnl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 1040, 50));

        pnl_content.setLayout(new java.awt.CardLayout());

        pnl_sanpham.setBackground(new java.awt.Color(248, 248, 255));
        pnl_sanpham.setPreferredSize(new java.awt.Dimension(1046, 571));

        jPanel2.setBackground(new java.awt.Color(248, 248, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(675, 471));

        TableDao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên", "Số lượng", "Trạng thái", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDao.setFocusable(false);
        TableDao.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableDao.setRowHeight(20);
        TableDao.setSelectionBackground(new java.awt.Color(255, 204, 204));
        TableDao.setShowGrid(false);
        TableDao.getTableHeader().setReorderingAllowed(false);
        TableDao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDao);

        tf_timkiemsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_timkiemsp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tên "));

        bnt_tksp.setBackground(new java.awt.Color(33, 150, 243));
        bnt_tksp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_tksp.setForeground(new java.awt.Color(255, 255, 255));
        bnt_tksp.setText("Tìm");
        bnt_tksp.setBorder(null);
        bnt_tksp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_tkspMouseClicked(evt);
            }
        });

        tf_timkiemmasp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_timkiemmasp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mã"));

        cbb_tkttsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_tkttsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng" }));
        cbb_tkttsp.setBorder(javax.swing.BorderFactory.createTitledBorder("Tình trạng"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_timkiemsp)
                .addGap(33, 33, 33)
                .addComponent(tf_timkiemmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cbb_tkttsp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(bnt_tksp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnt_tksp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbb_tkttsp)
                    .addComponent(tf_timkiemmasp)
                    .addComponent(tf_timkiemsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(248, 248, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 560));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(248, 248, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_tensp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tensp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tên sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.add(tf_tensp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 40));

        tf_giasp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_giasp.setText("1");
        tf_giasp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.add(tf_giasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 40));

        bnt_themsp.setBackground(new java.awt.Color(35, 221, 98));
        bnt_themsp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_themsp.setForeground(new java.awt.Color(255, 255, 255));
        bnt_themsp.setText("Thêm");
        bnt_themsp.setBorder(null);
        bnt_themsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_themspMouseClicked(evt);
            }
        });
        jPanel4.add(bnt_themsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 201, 80, 30));

        bnt_suasp.setBackground(new java.awt.Color(214, 207, 0));
        bnt_suasp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_suasp.setForeground(new java.awt.Color(255, 255, 255));
        bnt_suasp.setText("Sửa");
        bnt_suasp.setBorder(null);
        bnt_suasp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_suaspMouseClicked(evt);
            }
        });
        jPanel4.add(bnt_suasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 201, 80, 30));

        bnt_xoasp.setBackground(new java.awt.Color(225, 62, 39));
        bnt_xoasp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_xoasp.setForeground(new java.awt.Color(255, 255, 255));
        bnt_xoasp.setText("Xóa");
        bnt_xoasp.setBorder(null);
        bnt_xoasp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_xoaspMouseClicked(evt);
            }
        });
        jPanel4.add(bnt_xoasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 201, 80, 30));

        cbb_ttsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_ttsp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng" }));
        cbb_ttsp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trạng thái", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.add(cbb_ttsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, 150, -1));

        tf_soluongsp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_soluongsp.setText("1");
        tf_soluongsp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Số lượng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.add(tf_soluongsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 354, 250));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SẢN PHẨM");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 354, 40));

        lb_anhSP.setBackground(new java.awt.Color(204, 255, 204));
        lb_anhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_anhSP.setText("jLabel11");
        lb_anhSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ảnh", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.add(lb_anhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 350, 200));

        bnt_themanhSP.setText("IMG");
        bnt_themanhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_themanhSPMouseClicked(evt);
            }
        });
        jPanel3.add(bnt_themanhSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 20, 25));

        tf_anhsp.setText("ảnh");
        tf_anhsp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Đường dẫn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.add(tf_anhsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 320, -1));

        javax.swing.GroupLayout pnl_sanphamLayout = new javax.swing.GroupLayout(pnl_sanpham);
        pnl_sanpham.setLayout(pnl_sanphamLayout);
        pnl_sanphamLayout.setHorizontalGroup(
            pnl_sanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_sanphamLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pnl_sanphamLayout.setVerticalGroup(
            pnl_sanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sanphamLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(pnl_sanphamLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_content.add(pnl_sanpham, "card2");

        pnl_muahang.setBackground(new java.awt.Color(248, 248, 255));

        jPanel6.setBackground(new java.awt.Color(248, 248, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(390, 570));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Giá", "Số lượng", "Trạng thái", "Mã"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMenu.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableMenu.setRowHeight(25);
        TableMenu.setSelectionBackground(new java.awt.Color(255, 204, 204));
        TableMenu.setShowVerticalLines(false);
        TableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMenuMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableMenu);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 390, 460));

        jLabel3.setBackground(new java.awt.Color(248, 248, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NƯỚC UỐNG");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        tf_timspmenu.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm theo tên"));
        tf_timspmenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_timspmenuKeyReleased(evt);
            }
        });
        jPanel6.add(tf_timspmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 350, -1));

        pnl_muahang.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(248, 248, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 570));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(248, 248, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thông tin sản phẩm");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jPanel7.setBackground(new java.awt.Color(248, 248, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_tspMenu.setEditable(false);
        tf_tspMenu.setBackground(new java.awt.Color(255, 255, 255));
        tf_tspMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tspMenu.setText("Sữa tươi vinamilk chân châu đường đen không");
        tf_tspMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tên sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.add(tf_tspMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 23, 305, 40));

        tf_slspMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_slspMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_slspMenu.setText("99");
        tf_slspMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MUA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13))); // NOI18N
        jPanel7.add(tf_slspMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 10, 80, 60));

        bnt_themsoMenu.setBackground(new java.awt.Color(35, 221, 98));
        bnt_themsoMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnt_themsoMenu.setForeground(new java.awt.Color(255, 255, 255));
        bnt_themsoMenu.setText("+");
        bnt_themsoMenu.setBorder(null);
        bnt_themsoMenu.setPreferredSize(new java.awt.Dimension(47, 47));
        bnt_themsoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_themsoMenuActionPerformed(evt);
            }
        });
        jPanel7.add(bnt_themsoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 40, 60, 60));

        tf_giaspMenu.setEditable(false);
        tf_giaspMenu.setBackground(new java.awt.Color(255, 255, 255));
        tf_giaspMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_giaspMenu.setText("1");
        tf_giaspMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.add(tf_giaspMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 75, 90, 40));

        tf_trthaisp.setEditable(false);
        tf_trthaisp.setBackground(new java.awt.Color(255, 255, 255));
        tf_trthaisp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_trthaisp.setText("Còn hàng");
        tf_trthaisp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tình trạng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.add(tf_trthaisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 75, 134, 40));

        bnt_xoasphd.setBackground(new java.awt.Color(225, 62, 39));
        bnt_xoasphd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bnt_xoasphd.setForeground(new java.awt.Color(255, 255, 255));
        bnt_xoasphd.setText("XÓA");
        bnt_xoasphd.setBorder(null);
        bnt_xoasphd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_xoasphdMouseClicked(evt);
            }
        });
        jPanel7.add(bnt_xoasphd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 60, 60));

        tf_slconspMenu.setEditable(false);
        tf_slconspMenu.setBackground(new java.awt.Color(255, 255, 255));
        tf_slconspMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_slconspMenu.setText("99");
        tf_slconspMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Còn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.add(tf_slconspMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 75, 80, 40));
        tf_slconspMenu.getAccessibleContext().setAccessibleName("Còn\n");

        tf_maspMenu.setEditable(false);
        tf_maspMenu.setBackground(new java.awt.Color(255, 255, 255));
        tf_maspMenu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_maspMenu.setText("100000");
        tf_maspMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.add(tf_maspMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, 60, 40));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 630, 130));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Số lượng", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableHoadon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableHoadon.setRowHeight(20);
        TableHoadon.setSelectionBackground(new java.awt.Color(255, 204, 204));
        TableHoadon.setShowVerticalLines(false);
        jScrollPane5.setViewportView(TableHoadon);

        jPanel8.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 460, 230));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("HÓA ĐƠN");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        tf_mahoadon.setEditable(false);
        tf_mahoadon.setBackground(new java.awt.Color(255, 255, 255));
        tf_mahoadon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_mahoadon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_mahoadon.setText("*****X");
        tf_mahoadon.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã hóa đơn"));
        jPanel8.add(tf_mahoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 40));

        tf_ngayhoadon.setEditable(false);
        tf_ngayhoadon.setBackground(new java.awt.Color(255, 255, 255));
        tf_ngayhoadon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_ngayhoadon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_ngayhoadon.setText("yyyy-MM-dd");
        tf_ngayhoadon.setBorder(javax.swing.BorderFactory.createTitledBorder("Ngày mua"));
        jPanel8.add(tf_ngayhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("TỔNG:");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 70, 50));

        tf_manv.setEditable(false);
        tf_manv.setBackground(new java.awt.Color(255, 255, 255));
        tf_manv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_manv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_manv.setText("Nhân viên");
        tf_manv.setBorder(javax.swing.BorderFactory.createTitledBorder("Mã nhân viên"));
        jPanel8.add(tf_manv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 40));

        lb_tongtien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_tongtien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tongtien.setText("9000000");
        lb_tongtien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VNĐ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel8.add(lb_tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 370, 50));

        tf_tennv.setEditable(false);
        tf_tennv.setBackground(new java.awt.Color(255, 255, 255));
        tf_tennv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tennv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_tennv.setText("Tên nhân viên");
        tf_tennv.setBorder(javax.swing.BorderFactory.createTitledBorder("Tên nhân viên"));
        jPanel8.add(tf_tennv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 40));

        bnt_thanhtoan.setBackground(new java.awt.Color(35, 221, 98));
        bnt_thanhtoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnt_thanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        bnt_thanhtoan.setText("THANH TOÁN");
        bnt_thanhtoan.setBorder(null);
        bnt_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_thanhtoanActionPerformed(evt);
            }
        });
        jPanel8.add(bnt_thanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 630, 360));

        pnl_muahang.add(jPanel5);

        pnl_content.add(pnl_muahang, "card5");

        jPanel1.setBackground(new java.awt.Color(248, 248, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LỊCH SỬ ");

        TableLSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Ngày", "Tổng", "Nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableLSHD.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableLSHD.setRowHeight(25);
        TableLSHD.setShowVerticalLines(false);
        TableLSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableLSHDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableLSHD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 240, 245));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("CHI TIẾT HÓA ĐƠN");

        ta_ndlshd.setEditable(false);
        ta_ndlshd.setColumns(20);
        ta_ndlshd.setRows(5);
        jScrollPane6.setViewportView(ta_ndlshd);

        tf_tkhoadon.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mã hóa đơn"));

        tf_dhnv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tên nhân viên"));

        bnt_timcthd.setBackground(new java.awt.Color(33, 150, 243));
        bnt_timcthd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_timcthd.setForeground(new java.awt.Color(255, 255, 255));
        bnt_timcthd.setText("Tìm");
        bnt_timcthd.setBorder(null);
        bnt_timcthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_timcthdMouseClicked(evt);
            }
        });

        cbb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb1.setBorder(javax.swing.BorderFactory.createTitledBorder("Phân trang"));
        cbb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(33, 150, 243));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("In");
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(tf_tkhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_dhnv, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnt_timcthd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane6)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_tkhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_dhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbb1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(bnt_timcthd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_lichsuhdLayout = new javax.swing.GroupLayout(pnl_lichsuhd);
        pnl_lichsuhd.setLayout(pnl_lichsuhdLayout);
        pnl_lichsuhdLayout.setHorizontalGroup(
            pnl_lichsuhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lichsuhdLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_lichsuhdLayout.setVerticalGroup(
            pnl_lichsuhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_content.add(pnl_lichsuhd, "card4");

        pnl_nhanvien.setBackground(new java.awt.Color(248, 248, 255));
        pnl_nhanvien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("THÔNG TIN");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_nhanvien.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 500, 50));

        TableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CMND/CCCD", "Họ và tên", "Địa chỉ", "Ngày sinh", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableNV.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableNV.setShowVerticalLines(false);
        TableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNV);

        pnl_nhanvien.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, 530, 450));

        jLabel10.setBackground(new java.awt.Color(248, 248, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NHÂN VIÊN");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_nhanvien.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 50));

        lb_anhNV.setBackground(new java.awt.Color(255, 51, 0));
        lb_anhNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ảnh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        pnl_nhanvien.add(lb_anhNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 170, 200));

        tf_idNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_idNV.setText("23331235");
        tf_idNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CMND/CCCD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnl_nhanvien.add(tf_idNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 59, 290, 40));

        tf_tenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tenNV.setText("Tran Van A");
        tf_tenNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Họ và tên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnl_nhanvien.add(tf_tenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 290, 40));

        tf_diachiNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_diachiNV.setText("99 An Dương Vương, Phường 16, Quận 8");
        tf_diachiNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Địa chỉ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnl_nhanvien.add(tf_diachiNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 165, 290, 36));

        bnt_xoaNV.setBackground(new java.awt.Color(225, 62, 39));
        bnt_xoaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_xoaNV.setForeground(new java.awt.Color(255, 255, 255));
        bnt_xoaNV.setText("Xóa");
        bnt_xoaNV.setBorder(null);
        bnt_xoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_xoaNVMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(bnt_xoaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 50, 30));

        bnt_themNV.setBackground(new java.awt.Color(35, 221, 98));
        bnt_themNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_themNV.setForeground(new java.awt.Color(255, 255, 255));
        bnt_themNV.setText("Thêm");
        bnt_themNV.setBorder(null);
        bnt_themNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_themNVMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(bnt_themNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 60, 30));

        bnt_suaNV.setBackground(new java.awt.Color(214, 207, 0));
        bnt_suaNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_suaNV.setForeground(new java.awt.Color(255, 255, 255));
        bnt_suaNV.setText("Sửa");
        bnt_suaNV.setBorder(null);
        bnt_suaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_suaNVMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(bnt_suaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 50, 30));

        tf_duongdananhNV.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Đường dẫn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnl_nhanvien.add(tf_duongdananhNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 380, 40));

        bnt_tkNV.setBackground(new java.awt.Color(33, 150, 243));
        bnt_tkNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_tkNV.setForeground(new java.awt.Color(255, 255, 255));
        bnt_tkNV.setText("Tìm");
        bnt_tkNV.setBorder(null);
        bnt_tkNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_tkNVMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(bnt_tkNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 40));

        tf_tkidNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tkidNV.setText("233302145");
        tf_tkidNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CMND/CCCD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnl_nhanvien.add(tf_tkidNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 40));

        tf_tktenNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tktenNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Họ và tên ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnl_nhanvien.add(tf_tktenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 250, 40));

        cld_nsNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        cld_nsNV.setDateFormatString("yyyy-MM-dd");
        pnl_nhanvien.add(cld_nsNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 140, 45));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("*SẢN PHẨM có mã và tên là duy nhất, thêm, sửa nếu điền giá\nkhông đúng mặc định sẽ thêm 1 hoặc thông báo lỗi\n\n*MUA HÀNG không trùng tên sản phẩm, tối đa 10 sản phẩm,nếu số\nlượng không đúng thì xóa rồi thêm lại, số lượng <0||>99||là \nchữ thì mặc định 1\n\n*LỊCH SỬ ghi lại chi tiết hóa đơn của nhân viên\n*NHÂN VIÊN không sửa được CMND/CCCD, không xóa đc nhân viên\nđã làm hóa đơn\n*THỐNG KÊ doanh thu, sô hóa đơn mỗi nhân viên");
        jTextArea1.setPreferredSize(new java.awt.Dimension(388, 155));
        jScrollPane7.setViewportView(jTextArea1);

        pnl_nhanvien.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 500, 180));

        tf_sdtnv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_sdtnv.setText("01248574120");
        tf_sdtnv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Số điện thoại", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnl_nhanvien.add(tf_sdtnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 140, 45));

        btn_anhnv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_anhnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anhnvMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(btn_anhnv, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 60, 40));

        bnt_excelNV.setBackground(new java.awt.Color(16, 124, 65));
        bnt_excelNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt_excelNV.setForeground(new java.awt.Color(255, 255, 255));
        bnt_excelNV.setText("Excel");
        bnt_excelNV.setBorder(null);
        bnt_excelNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_excelNVMouseClicked(evt);
            }
        });
        pnl_nhanvien.add(bnt_excelNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, 50, 30));

        pnl_content.add(pnl_nhanvien, "card3");

        pnl_thongke.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        pnl_tk2.setBackground(new java.awt.Color(255, 255, 0));
        pnl_tk2.setPreferredSize(new java.awt.Dimension(0, 280));

        javax.swing.GroupLayout pnl_tk2Layout = new javax.swing.GroupLayout(pnl_tk2);
        pnl_tk2.setLayout(pnl_tk2Layout);
        pnl_tk2Layout.setHorizontalGroup(
            pnl_tk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pnl_tk2Layout.setVerticalGroup(
            pnl_tk2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_thongkeLayout = new javax.swing.GroupLayout(pnl_thongke);
        pnl_thongke.setLayout(pnl_thongkeLayout);
        pnl_thongkeLayout.setHorizontalGroup(
            pnl_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongkeLayout.createSequentialGroup()
                .addGroup(pnl_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_tk2, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_thongkeLayout.setVerticalGroup(
            pnl_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongkeLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_tk2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        pnl_content.add(pnl_thongke, "card6");

        getContentPane().add(pnl_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_themspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_themspMouseClicked
        String masp, tensp, anhsp, ttsp;
        Random rand = new Random();
        masp = String.valueOf(1 + rand.nextInt(100000));
        tensp = tf_tensp.getText();
        anhsp = tf_anhsp.getText();
        ttsp = cbb_ttsp.getSelectedItem().toString();
        System.out.println("d1124: " + cbb_ttsp.getSelectedItem().toString());
        try{
            int giasp =tf_giasp.getText().length()>6|| Integer.parseInt(tf_giasp.getText())<1 ? 1:Integer.parseInt(tf_giasp.getText());
            int soluongsp =Integer.parseInt(tf_soluongsp.getText())>99 || Integer.parseInt(tf_soluongsp.getText())<1 ? 0:Integer.parseInt(tf_soluongsp.getText());
            if(soluongsp==0){
                cbb_ttsp.setSelectedIndex(1);
                ttsp = cbb_ttsp.getSelectedItem().toString();
            }
            if(soluongsp > 0&& soluongsp <=99){
                cbb_ttsp.setSelectedIndex(0);
                ttsp = cbb_ttsp.getSelectedItem().toString();
            }
        if (JOptionPane.showConfirmDialog(this, "Xác nhận thêm sản phẩm") == 0) {
            sanphamdao spdaomoi = new sanphamdao(masp, tensp, anhsp,soluongsp ,ttsp, giasp);
            if (CheckDao.CheckThem(spdaomoi) == true) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
                spdao = CSDLQueryDao.XuatSanPhamDao();
                xuatspDao(spdao);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi, thêm sản phẩm");
            }
        }
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Thêm, Phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            tf_giasp.setText("1");
            tf_soluongsp.setText("1");
        }
    }//GEN-LAST:event_bnt_themspMouseClicked

    private void bnt_suaspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_suaspMouseClicked
        String masp, tensp, thsp, clsp, anhsp, ttsp;
        int giasp, vt;
        vt = TableDao.getSelectedRow();
        tensp = tf_tensp.getText();
        anhsp = tf_anhsp.getText();
        ttsp = cbb_ttsp.getSelectedItem().toString(); 
        System.out.println("d1209: " + ttsp);
        try{
            giasp =tf_giasp.getText().length()>6|| Integer.parseInt(tf_giasp.getText())<1 ? 1:Integer.parseInt(tf_giasp.getText());
            int soluongsp =Integer.parseInt(tf_soluongsp.getText())>99 || Integer.parseInt(tf_soluongsp.getText())<0 ? 1:Integer.parseInt(tf_soluongsp.getText());
            if(soluongsp==0){
                cbb_ttsp.setSelectedIndex(1);
                ttsp = cbb_ttsp.getSelectedItem().toString();
            }
            if(soluongsp > 0&& soluongsp <=99){
                cbb_ttsp.setSelectedIndex(0);
                ttsp = cbb_ttsp.getSelectedItem().toString();
            }
            if (JOptionPane.showConfirmDialog(this, "Xác nhận sửa sản phẩm") == 0) {
            spdao.get(vt).setTensp(tensp);
            spdao.get(vt).setAnhsp(anhsp);
            spdao.get(vt).setSoluongsp(soluongsp);
            spdao.get(vt).setTinhtrangsp(ttsp);
            spdao.get(vt).setGiasp(giasp);
            System.out.println(spdao.get(vt));
            if (CheckDao.CheckSua(spdao.get(vt)) == true) {
                JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công");
                spdao = CSDLQueryDao.XuatSanPhamDao();
                xuatspDao(spdao);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi, sửa sản phẩm", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        }catch(HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Thêm, Phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
            tf_giasp.setText("1");
            tf_soluongsp.setText("1");
        }
        
    }//GEN-LAST:event_bnt_suaspMouseClicked

    private void bnt_xoaspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_xoaspMouseClicked
        int vt;
        vt = TableDao.getSelectedRow();
        if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa sản phẩm") == 0) {
            if (CheckDao.CheckXoa(spdao.get(vt)) == true) {
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công");
                spdao = CSDLQueryDao.XuatSanPhamDao();
                xuatspDao(spdao);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi xóa sản phẩm");
            }
        }
    }//GEN-LAST:event_bnt_xoaspMouseClicked

    private void TableDaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDaoMouseClicked
        int vt = TableDao.getSelectedRow();
        tf_tensp.setText(TableDao.getValueAt(vt, 2).toString());
        tf_soluongsp.setText(TableDao.getValueAt(vt, 3).toString());
        cbb_ttsp.setSelectedItem(TableDao.getValueAt(vt, 4).toString());
        tf_giasp.setText(TableDao.getValueAt(vt, 5).toString().replace(",", ""));
        tf_anhsp.setText(spdao.get(vt).getAnhsp());
        ImageIcon iconSP = new ImageIcon(spdao.get(vt).getAnhsp());
        Image imgSP = iconSP.getImage().getScaledInstance(lb_anhSP.getWidth(), lb_anhSP.getHeight(), Image.SCALE_SMOOTH);
        lb_anhSP.setIcon(new ImageIcon(imgSP));
    }//GEN-LAST:event_TableDaoMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        pnl_content.removeAll();
        pnl_content.add(pnl_nhanvien);
        xuatnvDao(nvdao);  
        ImageIcon ic=new ImageIcon("../QuanLyBanNuoc/src/images/61-camera-outline.png");  
//        Image imgNV = ic.getImage().getScaledInstance(jButton3.getWidth(), jButton3.getHeight(), Image.SCALE_SMOOTH);
        btn_anhnv.setIcon(new ImageIcon(ic.getImage().getScaledInstance(btn_anhnv.getWidth(), btn_anhnv.getHeight(), Image.SCALE_SMOOTH)));
        pnl_content.validate();
        pnl_content.repaint();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pnl_content.removeAll();
        pnl_content.add(pnl_sanpham);
        xuatspDao(spdao);
        pnl_content.validate();
        pnl_content.repaint();
    }//GEN-LAST:event_jButton1MouseClicked

    private void bnt_themNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_themNVMouseClicked
        try{
            String idNV, tenNV, diachiNV, ngaysinhNV, anhNV, sdtNV;
            idNV = tf_idNV.getText();
            tenNV = tf_tenNV.getText();
            diachiNV = tf_diachiNV.getText();
            ngaysinhNV = sdf.format(cld_nsNV.getDate());
            anhNV = tf_duongdananhNV.getText();
            sdtNV=tf_sdtnv.getText();   
            if (JOptionPane.showConfirmDialog(this, "Xác nhận thêm nhân viên") == 0) {
                nhanviendao nvdaomoi = new nhanviendao(idNV, tenNV, diachiNV, ngaysinhNV, anhNV, sdtNV);
                System.out.println(nvdaomoi);
                if (CheckNV.CheckThem(nvdaomoi) == true) {
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                    nvdao = CSDLQueryNV.XuatNV();
                    xuatnvDao(nvdao);
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi thêm nhân viên");
                }
        }
        }catch(HeadlessException e){
             JOptionPane.showMessageDialog(this, "Chưa đầy đủ thông tin");
        }      
    }//GEN-LAST:event_bnt_themNVMouseClicked

    private void TableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNVMouseClicked
        try {
            int vt = TableNV.getSelectedRow();
            tf_idNV.setText(TableNV.getValueAt(vt, 0).toString());
            tf_tenNV.setText(TableNV.getValueAt(vt, 1).toString());
            tf_diachiNV.setText(TableNV.getValueAt(vt, 2).toString());
            cld_nsNV.setDate(sdf.parse(TableNV.getValueAt(vt, 3).toString()));
            tf_duongdananhNV.setText(nvdao.get(vt).getAnhnv());
            tf_sdtnv.setText(TableNV.getValueAt(vt, 4).toString());
            ImageIcon iconNV = new ImageIcon(nvdao.get(vt).getAnhnv());
            Image imgNV = iconNV.getImage().getScaledInstance(lb_anhNV.getWidth(), lb_anhNV.getHeight(), Image.SCALE_SMOOTH);
            lb_anhNV.setIcon(new ImageIcon(imgNV));
        } catch (ParseException ex) {
            Logger.getLogger(formquanly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableNVMouseClicked

    private void bnt_themanhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_themanhSPMouseClicked
        JFileChooser chonfile = new JFileChooser("../QuanLyBanNuoc/src/images");
        chonfile.showOpenDialog(null);
        File f = chonfile.getSelectedFile();
        String filename = f.getAbsolutePath();// lay duong dan tuyet doi
        tf_anhsp.setText(filename);
//        Image getAbsolutePath =null;
        ImageIcon iconSP = new ImageIcon(filename);
        Image imgNV = iconSP.getImage().getScaledInstance(lb_anhSP.getWidth(), lb_anhSP.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleimg = new ImageIcon(imgNV);
        lb_anhSP.setIcon(scaleimg);
    }//GEN-LAST:event_bnt_themanhSPMouseClicked

    private void bnt_suaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_suaNVMouseClicked
        String tenNV, diachiNV, ngaysinhNV, anhNV, sdtNV;
        int vt = TableNV.getSelectedRow();

        tenNV = tf_tenNV.getText();
        diachiNV = tf_diachiNV.getText();
        ngaysinhNV = sdf.format(cld_nsNV.getDate());
        anhNV = tf_duongdananhNV.getText();
        sdtNV =tf_sdtnv.getText();
        if (JOptionPane.showConfirmDialog(this, "Xác nhận sửa nhân viên") == 0) {
            nvdao.get(vt).setTennv(tenNV);
            nvdao.get(vt).setDiachinv(diachiNV);
            nvdao.get(vt).setNgaysinhnv(ngaysinhNV);
            nvdao.get(vt).setAnhnv(anhNV);
            nvdao.get(vt).setSdtnv(sdtNV);
            System.out.println("d1182 "+nvdao.get(vt));
            if (CheckNV.CheckSua(nvdao.get(vt)) == true) {
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công");
                nvdao = CSDLQueryNV.XuatNV();
                xuatnvDao(nvdao);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_bnt_suaNVMouseClicked

    private void bnt_xoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_xoaNVMouseClicked
        if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa nhân viên") == 0) {
            System.out.println(nvdao.get(TableNV.getSelectedRow()));
            if (CheckNV.CheckXoa(nvdao.get(TableNV.getSelectedRow())) == true) {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công");

                nvdao = CSDLQueryNV.XuatNV();
                xuatnvDao(nvdao);

            } else {
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_bnt_xoaNVMouseClicked

    private void bnt_tkspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_tkspMouseClicked
        String tksp = tf_timkiemsp.getText();
        String tkmasp = tf_timkiemmasp.getText();
        String tkttsp=cbb_tkttsp.getSelectedItem().toString();
        
        System.out.println("d1102: " + tf_timkiemmasp.getText());
        if (tksp.isEmpty() && tkmasp.isEmpty()) {
            spdao = CSDLQueryDao.XuatSanPhamDao();
            xuatspDao(spdao);
        } else {
            spdao = CSDLQueryDao.timkiemSP(tksp, tkmasp, tkttsp);
            xuatspDao(spdao);
        }
    }//GEN-LAST:event_bnt_tkspMouseClicked

    private void bnt_themsoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_themsoMenuActionPerformed

        int tongtien = 0,vt;
        String tensp = tf_tspMenu.getText();
        String tthsp = tf_trthaisp.getText();
        String masp = tf_maspMenu.getText();
        try {
            int giasp = Integer.parseInt(tf_giaspMenu.getText());
            int slmuasp = Integer.parseInt(tf_slspMenu.getText());
//          int slmuasp = tf_slspMenu.getText().length() > 2 || Integer.parseInt(tf_slspMenu.getText()) < 1 ? 1 : Integer.parseInt(tf_slspMenu.getText());
            int slsp = Integer.parseInt(tf_slconspMenu.getText());
            vt = TableHoadon.getRowCount()+1;
            
            Object[] roww = {masp, tf_tspMenu.getText(), slmuasp, tf_giaspMenu.getText()};
            
            if (TableHoadon.getRowCount() == 0 && tthsp.equals("Còn hàng")) {
                if(slmuasp > slsp || slmuasp <=0) {
                    JOptionPane.showMessageDialog(this, "Lỗi số lượng hoặc vượt quá số lượng","Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                }else{
                    Modelhoadon.addRow(roww);
                    tongtien = 0;
                    for (int i = 0; i < TableHoadon.getRowCount(); i++) {
                        tongtien = tongtien + (Integer.parseInt(TableHoadon.getValueAt(i, 2).toString())*Integer.parseInt(TableHoadon.getValueAt(i, 3).toString()));
                    }
                    lb_tongtien.setText(df.format(tongtien));
                    return;
                }
            }

            if (TableHoadon.getRowCount() > 0 && TableHoadon.getRowCount() < 10 && tthsp.equals("Còn hàng") ) {
                if (kiemtratrungten(tensp)) {
                    JOptionPane.showMessageDialog(this, "Trùng sản phẩm","Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                } 
                if(slmuasp > slsp || slmuasp <=0){
                    JOptionPane.showMessageDialog(this, "Lỗi số lượng hoặc vượt quá số lượng","Lỗi",JOptionPane.ERROR_MESSAGE);
                    return;
                }else{
                     Modelhoadon.addRow(roww);
                     tongtien = 0;
                    for (int i = 0; i < TableHoadon.getRowCount(); i++) {
                        tongtien = tongtien + (Integer.parseInt(TableHoadon.getValueAt(i, 2).toString())*Integer.parseInt(TableHoadon.getValueAt(i, 3).toString()));
                    }
                    lb_tongtien.setText(df.format(tongtien));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hết hàng hoặc Tối đa 10 sản phẩm");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Thêm hóa đơn lỗi, phải là số","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bnt_themsoMenuActionPerformed

    public boolean kiemtratrungten(String ten) {
        boolean flag = true;
        for (int j = 0; j < TableHoadon.getRowCount(); j++) {
            if (ten.equals(TableHoadon.getValueAt(j, 1).toString())) {
                flag = true;
                break;
            } else {
                flag = false;
            }
        }
        System.out.println("d1460 " + flag);
        return flag;
    }

    private void bnt_muahangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_muahangMouseClicked
        pnl_content.removeAll();
        pnl_content.add(pnl_muahang);

        spmenu = CSDLQueryDao.XuatSanPhamDao();
        xuatspMenu(spmenu);

        System.out.println("Dòng: " + CSDLQueryHD.Demsodong());

        tf_mahoadon.setText(String.format("%06d", CSDLQueryHD.Demsodong() + 1));// tổng cộng sáu số, bắt đầu từ 1 thì những số trc sẽ là 0
        
        Modelhoadon = (DefaultTableModel) TableHoadon.getModel();
//        Modelhoadon.setRowCount(0);
        
        tf_ngayhoadon.setText(lttime.toString());
//        lb_tongtien.setText("0");
        
        pnl_content.validate();
        pnl_content.repaint();
    }//GEN-LAST:event_bnt_muahangMouseClicked

    private void TableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMenuMouseClicked
        int vt = TableMenu.getSelectedRow();
        tf_tspMenu.setText(TableMenu.getValueAt(vt, 1).toString());
        tf_slspMenu.setText("1");
        tf_giaspMenu.setText(TableMenu.getValueAt(vt, 2).toString().replace(",", ""));
        tf_slconspMenu.setText(TableMenu.getValueAt(vt, 3).toString());
        tf_trthaisp.setText(TableMenu.getValueAt(vt, 4).toString());
        tf_maspMenu.setText(TableMenu.getValueAt(vt, 5).toString());
    }//GEN-LAST:event_TableMenuMouseClicked

    private void bnt_xoasphdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_xoasphdMouseClicked
        int vt = TableHoadon.getSelectedRow();
        int tong = Integer.parseInt(lb_tongtien.getText().replace(",", "")) - (Integer.parseInt(TableHoadon.getValueAt(vt, 3).toString())*Integer.parseInt(TableHoadon.getValueAt(vt, 2).toString()));
        
//        chitiet.get
//        TableHoadon.get
    int vt2=TableHoadon.getSelectedRow();
        System.out.println(vt2);
        System.out.println(chitiet.toString());
        lb_tongtien.setText(df.format(tong));
        Modelhoadon.removeRow(vt);
    }//GEN-LAST:event_bnt_xoasphdMouseClicked

    private void tf_timspmenuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_timspmenuKeyReleased
        String tk = tf_timspmenu.getText();
        System.out.println(spmenu.size());
        xuatspMenu(CSDLQueryDao.TimkiemMenu(tk));
        if (tk.isEmpty()) {
            xuatspMenu(spmenu);
        }
    }//GEN-LAST:event_tf_timspmenuKeyReleased

    private void bnt_lichsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_lichsuMouseClicked
              
        pnl_content.removeAll();
        pnl_content.add(pnl_lichsuhd);
        
        lshddao = CSDLQueryHD.XuatHoaDonDao();
        xuatlshoadon(lshddao);
        
        cbb1.removeAllItems();
        int listtempp=CSDLQueryHD.Demsodong()/5 !=0 ? Math.round(CSDLQueryHD.Demsodong()/5)+1:Math.round(CSDLQueryHD.Demsodong()/5);
        for(int i=0; i<listtempp; i++){
            cbb1.addItem(String.valueOf(i+1));
        }
        xuatlshoadon(CSDLQueryHD.Phantrangls(0));
            
        pnl_content.validate();
        pnl_content.repaint();
    }//GEN-LAST:event_bnt_lichsuMouseClicked

    private void bnt_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_thanhtoanActionPerformed
        String s1, s2, s3 = "", s5;
        int s4;;
        s1 = tf_mahoadon.getText();
        s2 = tf_ngayhoadon.getText();
        s4 = Integer.parseInt(lb_tongtien.getText().replace(",", ""));
        s5 = tf_manv.getText();
        System.out.println("d1557: " +TableHoadon.getRowCount());
        for (int i = 0; i < TableHoadon.getRowCount(); i++) {
            s3 = s3 + "Tên: " + TableHoadon.getValueAt(i, 1).toString() + "   X   "
                    + TableHoadon.getValueAt(i, 2).toString() + "          -Giá: " + TableHoadon.getValueAt(i, 3).toString() + "\n";
        
        }
       
        hoadondao hddao = new hoadondao(s1, s2, s3, s4, s5, tf_tennv.getText());
     
        System.out.println(chitiet.toString());
        
        if (TableHoadon.getRowCount() > 0 && tf_tennv.getText().isEmpty()!=true) {
            for (int i = 0; i < TableHoadon.getRowCount(); i++){
                chitiethoadon ctiet=new chitiethoadon(s1,TableHoadon.getValueAt(i, 0).toString(), Integer.parseInt(TableHoadon.getValueAt(i, 2).toString()),  Integer.parseInt(TableHoadon.getValueAt(i, 3).toString()));
                chitiet.add(ctiet);
            }
            if (CheckHD.CheckThem(hddao, chitiet) )  {
                JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công");
                for (int i = 0; i < TableHoadon.getRowCount(); i++){
                    if(CSDLQueryDao.CapnhatSP(TableHoadon.getValueAt(i, 1).toString(), Integer.parseInt(TableHoadon.getValueAt(i, 2).toString()))){
                }
            }
                chitiet.clear();
                Modelhoadon.setRowCount(0);
                lb_tongtien.setText("0");
            } else  JOptionPane.showMessageDialog(this, "Thêm hóa đơn thất bại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            
            spdao = CSDLQueryDao.XuatSanPhamDao(); 
            xuatspDao(spdao);
            spmenu = CSDLQueryDao.XuatSanPhamDao(); 
            xuatspMenu(spmenu);
        } else {
             JOptionPane.showMessageDialog(this, "1.Lỗi chưa đăng nhập \n 2.Không có sản phẩm nào", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        tf_mahoadon.setText(String.valueOf(String.format("%06d", CSDLQueryHD.Demsodong() + 1)));
    }//GEN-LAST:event_bnt_thanhtoanActionPerformed

    private void bnt_tkNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_tkNVMouseClicked
        String s1, s2;
        s1 = tf_tkidNV.getText();
        s2 = tf_tktenNV.getText();
        xuatnvDao(CSDLQueryNV.TimkiemNV(s1, s2));
    }//GEN-LAST:event_bnt_tkNVMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        CSDLQueryNV.idNV = "";
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
        chitiet.clear();
    }//GEN-LAST:event_jButton7MouseClicked

    private void TableLSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableLSHDMouseClicked
        int vt = TableLSHD.getSelectedRow();
//        ta_ndlshd.setText(
//                "\nHÓA ĐƠN\n"
//                + "\t\nMã hóa đơn: " + lshddao.get(vt).getMahd()
//                + "\nNgày mua: " + lshddao.get(vt).getNgayhd()
//                + "\nTên nhân viên: " + lshddao.get(vt).getTenNVdh()
//                + "\n\n=======================================================================\n\n"
//                + lshddao.get(vt).getNoidunghd()
//                + "\n=======================================================================\n"
//                + "\nTỔNG: " + TableLSHD.getValueAt(vt, 3).toString() + " VNĐ"
//        );
        System.out.print(TableLSHD.getValueAt(vt, 1));
        CSDLQueryHD lshd=new CSDLQueryHD();
        ta_ndlshd.setText( lshd.display(TableLSHD.getValueAt(vt, 1).toString()) );
    }//GEN-LAST:event_TableLSHDMouseClicked

///===============================================THỐNG KÊ====================================
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        pnl_content.removeAll();
        pnl_content.add(pnl_thongke);
        ////////////////////////////
        ChartPanel cp = new ChartPanel(CSDLQueryTK.ThongKeDoanhThu());
        cp.setSize(jPanel10.getWidth(), jPanel10.getHeight());
        jPanel10.removeAll();
        jPanel10.add(cp);
        ///////////////////////////
        ChartPanel cp1 = new ChartPanel(CSDLQueryTK.ThongKeHoaDonNV());
        cp1.setSize(pnl_tk2.getWidth(), pnl_tk2.getHeight());
        pnl_tk2.removeAll();
        pnl_tk2.add(cp1);
        //////////////////
        pnl_content.validate();
        pnl_content.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

///===============================================THỐNG KÊ====================================
    
    private void btn_anhnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anhnvMouseClicked
        JFileChooser chonfile = new JFileChooser("../QuanLyBanNuoc/src/images");
        chonfile.showOpenDialog(null);
        File f = chonfile.getSelectedFile(); //https://stackoverflow.com/questions/4984636/writing-getselectedfile-as-a-string-java
        String filename = f.getAbsolutePath();
        tf_duongdananhNV.setText(filename);
//        Image getAbsolutePath =null;
        ImageIcon iconSP = new ImageIcon(filename);
        Image imgNV = iconSP.getImage().getScaledInstance(lb_anhNV.getWidth(), lb_anhNV.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleimg = new ImageIcon(imgNV);
        lb_anhNV.setIcon(scaleimg);
    }//GEN-LAST:event_btn_anhnvMouseClicked

    private void bnt_timcthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_timcthdMouseClicked
        String s1, s2;
        s1 = tf_tkhoadon.getText();
        s2 = tf_dhnv.getText();
        if(s1.isEmpty()&&s2.isEmpty()){
            lshddao=CSDLQueryHD.XuatHoaDonDao();
            xuatlshoadon(lshddao);
        }else xuatlshoadon(CSDLQueryHD.TimHoaDonDao(s1, s2));
    }//GEN-LAST:event_bnt_timcthdMouseClicked

    private void cbb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb1ActionPerformed
        xuatlshoadon( CSDLQueryHD.Phantrangls(1));
        int vt= cbb1.getSelectedIndex()*5;
        xuatlshoadon(CSDLQueryHD.Phantrangls(vt));
    }//GEN-LAST:event_cbb1ActionPerformed
    
    ///============================================XUẤT FILE EXCEL========================================
    private FileOutputStream fos = null;
    private BufferedOutputStream bos = null;
    private JFileChooser jfc = null;

    private void XuatFileExcel(XSSFRow row, XSSFCell cell, XSSFSheet excelSheet, XSSFWorkbook ExcelExport, DefaultTableModel model) {
        String Value;
        for (int i = 0; i < model.getRowCount(); i++) {
            row = excelSheet.createRow(i + 1);
            for (int j = 0; j < model.getColumnCount(); j++) {
                cell = row.createCell(j, CellType.STRING);
                if (model.getValueAt(i, j) == null) {
                    Value = "";
                } else {
                    Value = model.getValueAt(i, j).toString();
                }
                cell.setCellValue(Value);
            }
        }
        String file = jfc.getSelectedFile().getAbsolutePath() + ".xlsx";
        try {
            fos = new FileOutputStream(file);
            bos = new BufferedOutputStream(fos);
            ExcelExport.write(bos);
            JOptionPane.showMessageDialog(this, "Xuất file excel thành công" + "\n" + "Đường dẫn của file: " + file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MultiOptionForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MultiOptionForm.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (bos != null) {
                try {
                    bos.close();
                } catch (IOException ex) {
                    Logger.getLogger(MultiOptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(MultiOptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (ExcelExport != null) {
                try {
                    ExcelExport.close();
                } catch (IOException ex) {
                    Logger.getLogger(MultiOptionForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    
    private void bnt_excelNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_excelNVMouseClicked
        jfc = new JFileChooser();
        jfc.setDialogTitle("Save as");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Excel File", "xlsx", "xls");
        jfc.setFileFilter(fnef);
        int choose = jfc.showSaveDialog(this);
        if (choose == JFileChooser.APPROVE_OPTION) {
            XSSFWorkbook ExcelExport = new XSSFWorkbook();
            XSSFSheet excelSheet = ExcelExport.createSheet("Thông tin nhân viên");
            XSSFRow row = excelSheet.createRow(0);
            XSSFCell cell = null;
//            cell = row.createCell(0);
//            cell.setCellValue("STT");
            cell = row.createCell(0);
            cell.setCellValue("CMND/CCCD");
            cell = row.createCell(1);
            cell.setCellValue("Họ và tên");
            cell = row.createCell(2);
            cell.setCellValue("Địa chỉ");
            cell = row.createCell(3);
            cell.setCellValue("Ngày sinh");
            cell = row.createCell(4);
            cell.setCellValue("Số điện thoại");
            cell = row.createCell(5);
            XuatFileExcel(row, cell, excelSheet, ExcelExport, Modelnv);
        }
    }//GEN-LAST:event_bnt_excelNVMouseClicked
    
    ////============================================XUẤT FILE EXCEL========================================
    
    ///========================================IN=================================================
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        try {
            ta_ndlshd.print();
        }catch(java.awt.print.PrinterException e){
            System.err.format("Ko thấy gì hết", e.getMessage());
        }
    }//GEN-LAST:event_jButton5MouseClicked

   ///========================================IN==================================================
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new formquanly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDao;
    private javax.swing.JTable TableHoadon;
    private javax.swing.JTable TableLSHD;
    private javax.swing.JTable TableMenu;
    private javax.swing.JTable TableNV;
    private javax.swing.JButton bnt_excelNV;
    private javax.swing.JButton bnt_lichsu;
    private javax.swing.JButton bnt_muahang;
    private javax.swing.JButton bnt_suaNV;
    private javax.swing.JButton bnt_suasp;
    private javax.swing.JButton bnt_thanhtoan;
    private javax.swing.JButton bnt_themNV;
    private javax.swing.JButton bnt_themanhSP;
    private javax.swing.JButton bnt_themsoMenu;
    private javax.swing.JButton bnt_themsp;
    private javax.swing.JButton bnt_timcthd;
    private javax.swing.JButton bnt_tkNV;
    private javax.swing.JButton bnt_tksp;
    private javax.swing.JButton bnt_xoaNV;
    private javax.swing.JButton bnt_xoasp;
    private javax.swing.JButton bnt_xoasphd;
    private javax.swing.JButton btn_anhnv;
    private javax.swing.JComboBox<String> cbb1;
    private javax.swing.JComboBox<String> cbb_tkttsp;
    private javax.swing.JComboBox<String> cbb_ttsp;
    private com.toedter.calendar.JDateChooser cld_nsNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_anhNV;
    private javax.swing.JLabel lb_anhSP;
    private javax.swing.JLabel lb_tongtien;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_lichsuhd;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_muahang;
    private javax.swing.JPanel pnl_nhanvien;
    private javax.swing.JPanel pnl_sanpham;
    private javax.swing.JPanel pnl_thongke;
    private javax.swing.JPanel pnl_tk2;
    private javax.swing.JTextArea ta_ndlshd;
    private javax.swing.JTextField tf_anhsp;
    private javax.swing.JTextField tf_dhnv;
    private javax.swing.JTextField tf_diachiNV;
    private javax.swing.JTextField tf_duongdananhNV;
    private javax.swing.JTextField tf_giasp;
    private javax.swing.JTextField tf_giaspMenu;
    private javax.swing.JTextField tf_idNV;
    private javax.swing.JTextField tf_mahoadon;
    private javax.swing.JTextField tf_manv;
    private javax.swing.JTextField tf_maspMenu;
    private javax.swing.JTextField tf_ngayhoadon;
    private javax.swing.JTextField tf_sdtnv;
    private javax.swing.JTextField tf_slconspMenu;
    private javax.swing.JTextField tf_slspMenu;
    private javax.swing.JTextField tf_soluongsp;
    private javax.swing.JTextField tf_tenNV;
    private javax.swing.JTextField tf_tennv;
    private javax.swing.JTextField tf_tensp;
    private javax.swing.JTextField tf_timkiemmasp;
    private javax.swing.JTextField tf_timkiemsp;
    private javax.swing.JTextField tf_timspmenu;
    private javax.swing.JTextField tf_tkhoadon;
    private javax.swing.JTextField tf_tkidNV;
    private javax.swing.JTextField tf_tktenNV;
    private javax.swing.JTextField tf_trthaisp;
    private javax.swing.JTextField tf_tspMenu;
    // End of variables declaration//GEN-END:variables
}
