package GUI;

import DAL.CSDLQueryNV;
import java.util.Arrays;
import javax.swing.*;

public class login extends javax.swing.JFrame {
    
    public login() { 
        initComponents();
        setLocationRelativeTo(null);// căn giữa màn hình     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_manhanvien = new javax.swing.JTextField();
        tf_matkhau = new javax.swing.JPasswordField();
        tf_tendangnhap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý bán hàng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 319, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ĐĂNG NHẬP");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 140, 30));

        tf_manhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.add(tf_manhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 205, 200, 50));

        tf_matkhau.setText("admin");
        tf_matkhau.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.add(tf_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, 50));

        tf_tendangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_tendangnhap.setText("admin");
        tf_tendangnhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên đăng nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.add(tf_tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String s1=tf_tendangnhap.getText();
        String s2=String.valueOf(tf_matkhau.getPassword());
//        String s3=tf_manhanvien.getText();
        String s3=tf_manhanvien.getText().equals("") ? "": tf_manhanvien.getText();
        System.out.println(s3);
        System.out.println(CSDLQueryNV.Dangnhap(s3));
        if (s1.equals("") || s2.equals("")) {
            JOptionPane.showMessageDialog(this, "Điền đầy đủ thông tin");
        }else{
            if(s1.equals("admin")&&s2.equals("admin")){
                if(CSDLQueryNV.Dangnhap(s3)==true){
                    JOptionPane.showMessageDialog(this, "Chào mừng: " + CSDLQueryNV.tenNV);           
                    formquanly fm=new formquanly();
                    fm.setVisible(true);
                    dispose();
                }else {
                    JOptionPane.showMessageDialog(this, "Chào mừng admin");           
                    formquanly fm=new formquanly();
                    fm.setVisible(true);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Sai mã nhân viên", "Sai", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_manhanvien;
    private javax.swing.JPasswordField tf_matkhau;
    private javax.swing.JTextField tf_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
